version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "java-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h984rawrr1ir"
s3_prefix = "java-app"
region = "us-east-1"
profile = "intellij"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
