Transform: AWS::Serverless-2016-10-31
Resources:
  didaticWaddleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 448
      Handler: org.example.Handler::handleRequest
      CodeUri: .
      Runtime: java11
      Role: LambdaCustomRole