Resources:
  didaticWaddleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 448
      Handler: org.example.Handler::handleRequest
      CodeUri: didaticWaddleFunction
      Runtime: java11
      Policies:
        - AWSLambdaBasicExecutionRole-c796f7ee-bffa-4f2a-bc63-85817a6247bc