Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: org.example.Handler::handleRequest
      CodeUri: Function
      Runtime: java8
